import { AbsoluteFill, useCurrentFrame, interpolate, spring } from "remotion";

const colors = {
  primary: '#3498db',
  secondary: '#f1c40f',
  background: '#2c3e50',
  highlight: '#e74c3c',
};

export default function MainScene() {
  const frame = useCurrentFrame();

  const titleOpacity = interpolate(frame, [0, 150], [0, 1], { extrapolate: 'clamp' });
  const titleScale = interpolate(frame, [0, 150], [0.5, 1], { extrapolate: 'clamp' });

  const contextOpacity = interpolate(frame, [150, 300], [0, 1], { extrapolate: 'clamp' });
  const contextScale = interpolate(frame, [150, 300], [0.5, 1], { extrapolate: 'clamp' });

  const coreConceptOpacity = interpolate(frame, [300, 500], [0, 1], { extrapolate: 'clamp' });
  const coreConceptScale = interpolate(frame, [300, 500], [0.5, 1], { extrapolate: 'clamp' });

  const keyInsightOpacity = interpolate(frame, [500, 700], [0, 1], { extrapolate: 'clamp' });
  const keyInsightScale = interpolate(frame, [500, 700], [0.5, 1], { extrapolate: 'clamp' });

  const summaryOpacity = interpolate(frame, [700, 900], [0, 1], { extrapolate: 'clamp' });
  const summaryScale = interpolate(frame, [700, 900], [0.5, 1], { extrapolate: 'clamp' });

  return (
    <AbsoluteFill style={{ backgroundColor: colors.background, fontFamily: 'Arial' }}>
      {/* Phase 1: Title and intro */}
      <div style={{
        opacity: titleOpacity,
        transform: `scale(${titleScale})`,
        fontSize: 48,
        color: colors.primary,
        fontWeight: 'bold',
        textAlign: 'center',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
      }}>
        Token Sequence Comparison
      </div>

      {/* Phase 2: Setup/context */}
      <div style={{
        opacity: contextOpacity,
        transform: `scale(${contextScale})`,
        fontSize: 24,
        color: colors.secondary,
        textAlign: 'center',
        position: 'absolute',
        top: '60%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
      }}>
        Comparing token sequences generated by different methods
      </div>

      {/* Phase 3: Core concept animation */}
      <div style={{
        opacity: coreConceptOpacity,
        transform: `scale(${coreConceptScale})`,
        fontSize: 24,
        color: colors.primary,
        textAlign: 'center',
        position: 'absolute',
        top: '40%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-around' }}>
          <div style={{ border: `1px solid ${colors.primary}`, padding: 20, borderRadius: 10 }}>
            Method 1
          </div>
          <div style={{ border: `1px solid ${colors.secondary}`, padding: 20, borderRadius: 10 }}>
            Method 2
          </div>
        </div>
      </div>

      {/* Phase 4: Key insight or comparison */}
      <div style={{
        opacity: keyInsightOpacity,
        transform: `scale(${keyInsightScale})`,
        fontSize: 24,
        color: colors.highlight,
        textAlign: 'center',
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-around' }}>
          <div style={{ border: `1px solid ${colors.primary}`, padding: 20, borderRadius: 10, backgroundColor: colors.highlight }}>
            Adaptive token assignment
          </div>
          <div style={{ border: `1px solid ${colors.secondary}`, padding: 20, borderRadius: 10 }}>
            EVATok framework
          </div>
        </div>
      </div>

      {/* Phase 5: Summary and conclusion */}
      <div style={{
        opacity: summaryOpacity,
        transform: `scale(${summaryScale})`,
        fontSize: 24,
        color: colors.primary,
        textAlign: 'center',
        position: 'absolute',
        top: '60%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
      }}>
        In conclusion, adaptive token assignment and the EVATok framework offer advantages in token sequence comparison
      </div>
    </AbsoluteFill>
  );
}